clockfix: Add basic clockfix infrastructure.
This just introduces the infrastructure and configuration
parts of CLOCKFIX patch. It doesn't change OSCam to actually
use CLOCK_MONOTONIC and doesn't switch time checks to milliseconds
instead of seconds.

This is just a preparation and shouldn't change OSCam's timing
behaviour.

WARNING: If you see build failure like this:

undefined reference to `pthread_condattr_setclock'

Report it in the forum and disable CLOCKFIX configuration.

`./config.sh -D CLOCKFIX`

Patch by: theparasol